"""empty message

Revision ID: 6d1369edb6de
Revises: 
Create Date: 2022-09-18 02:04:35.432044

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.json
import sqlalchemy_utils.types.password
import sqlalchemy_utils.types.uuid

# revision identifiers, used by Alembic.
revision = "6d1369edb6de"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column(
            "password", sqlalchemy_utils.types.password.PasswordType(), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("email_validated", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "sqlalchemy_storagebox",
        sa.Column("id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
        sa.Column("payload", sqlalchemy_utils.types.json.JSONType(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("FAILED", "PUBLISHED", "WAITING", name="statusenum"),
            nullable=True,
        ),
        sa.Column("retries", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("class_name", sa.String(), nullable=True),
        sa.Column("module_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sqlalchemy_storagebox")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
