"""empty message

Revision ID: 0cacc17e0fc3
Revises: 4274e739c168
Create Date: 2022-10-09 03:03:41.211679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0cacc17e0fc3"
down_revision = "4274e739c168"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
