"""empty message

Revision ID: 4274e739c168
Revises: 456d9fd5fbb1
Create Date: 2022-10-09 02:52:27.222010

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.uuid

# revision identifiers, used by Alembic.
revision = "4274e739c168"
down_revision = "456d9fd5fbb1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("uuid", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "uuid")
    # ### end Alembic commands ###
