"""empty message

Revision ID: 456d9fd5fbb1
Revises: 6d1369edb6de
Create Date: 2022-10-09 02:49:14.232118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "456d9fd5fbb1"
down_revision = "6d1369edb6de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("validation_token", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "validation_token")
    # ### end Alembic commands ###
